modLoader="javafml"
loaderVersion="[1,)"
license="${mod_license}"
issueTrackerURL="https://github.com/djayfresh/messybeds/issues"

[[mods]]
modId="${mod_id}"
version="${mod_version}"
displayName="${mod_name}"
displayURL="https://github.com/djayfresh/messybeds"
credits="Created by DJayFresh"
authors="DJayFresh"
description='''
Messy Beds. Sleeping leaves your bed unmade until you tidy it, beds turn down
when it is time to sleep, and every bed in the world is a messy bed.
'''

[[dependencies.${mod_id}]]
    modId="neoforge"
    type="required"
    versionRange="[${neo_version},)"
    ordering="NONE"
    side="BOTH"

[[dependencies.${mod_id}]]
    modId="minecraft"
    type="required"
    versionRange="${minecraft_version_range}"
    ordering="NONE"
    side="BOTH"
